### ISSUE TITLE
Use DB triggers to run views

### ISSUE THREAD

**Issue by fourlastor** [squanchy-dev/squanchy-firebase#15]
Right now we're using manually triggered functions to convert our data to views, ideally we should have a [Cloud Firestore Trigger](https://firebase.google.com/docs/functions/firestore-events) firing up the function.

Most likely we can go with `onWrite` and write/delete the record as required.

**Comment by fourlastor** [comment]
After a second analysis, this is likely not to work for us, it's hard to update only "what we need" because it might be nested inside some other view (e.g., a room might trigger an update on multiple events), so the best way is to update everything together when something changes.

This can't be done on DB triggers, because they're likely to happen all together (a batch of changes via `patch`), so for now the way to go will be invoking the functions together after updating the data (or with a single function that will trigger all the view updates).

**Comment by rock3r** [comment]
Agreed, let's close this
