### ISSUE TITLE
Accept "private" flag on patch for submissions

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-firebase#25]
We should be able to treat private submissions as such. Syx passes us that flag but we don't support it; it may come especially handy when/if we have a CMS/CFP platform of our own.

**Comment by fourlastor** [comment]
Hm I'd actually scrap this.

Patch is a hack put in place because we don't have a proper api, and it will be replaced by more specific endpoints in the future.

Right now we don't support that bit of functionality and I don't see us supporting it before we move to a proper api.

**Comment by rock3r** [comment]
Makes sense. I suppose this should be more about having that flag in our `Submission` model more than anything else.

**Comment by fourlastor** [comment]
Or just have a draft system, or whatever it'll be :) closing this for now
