### ISSUE TITLE
Import function from other conference system

### ISSUE THREAD

**Issue by friedger** [squanchy-dev/squanchy-firebase#59]
Add function template that allows to import the conference data from a 3rd party API into firestore.

**Comment by fourlastor** [comment]
@rock3r is this still relevant? I think patch covers it in case.

**Comment by rock3r** [comment]
It can be used but it's not the best thing. It's a hack to accommodate for Syx inability to generate data in a proper way. I'd keep this open to remind us we don't have a real API
